-- Create inquiries table for contact form submissions.
create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  full_name text not null,
  phone text not null,
  email text not null,
  legal_matter text not null,
  source text default 'website',
  created_at timestamptz not null default now()
);

-- Enable Row Level Security.
alter table public.inquiries enable row level security;

-- Public website visitors can submit inquiries.
drop policy if exists "Public can insert inquiries" on public.inquiries;
create policy "Public can insert inquiries"
on public.inquiries
for insert
to anon, authenticated
with check (true);

-- Only authenticated users (Supabase Auth) can read inquiries in admin panel.
drop policy if exists "Public can read inquiries" on public.inquiries;
drop policy if exists "Authenticated users can read inquiries" on public.inquiries;
create policy "Authenticated users can read inquiries"
on public.inquiries
for select
to authenticated
using (true);
